---

- name: Add repositories CentOS
  dnf:
    name: '{{ centos_repo }}'
    state: present
    update_cache: yes
  tags:
    - debian

- name: Install packages CentOS
  dnf:
    name: '{{ centos_packages }}'
    state: present
  tags:
    - debian

- name: Start services
  systemd:
    name: httpd
    state: started
    enabled: true
  tags:
    - debian

# - name: Add new GPG key
#   rpm_key:
#     url: https://packages.sury.org/php/apt.gpg 
#     state: present