---
# tasks file for lamp
- name: Sudo block
  become: yes
  block:
    - name: Add repository Ubuntu
      apt_repository:
        repo: 'ppa:ondrej/php'
      tags:
        - repository
      when: ansible_distribution == "Ubuntu"
      tags:
        - ubuntu

    - name: Block for Debian
      when: ansible_distribution == "Debian"
      import_tasks: debian_os.yml
      tags:
        - debian

    - name: Block for CentOS
      when: ansible_distribution == "CentOS"
      import_tasks: centos_os.yml
      tags:
        - centos
       
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      notify:
        - start apache2
        - start mysql
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: Deploy dynamix html
      template: 
        src: index.html.j2
        dest: /var/www/html/index.html
      tags:
        - template